import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  header: { alignItems: 'center', padding: 30, gap: 8 },
  avatarContainer: { width: 100, height: 100, borderRadius: 50, position: 'relative', backgroundColor: '#eee', justifyContent: 'center', alignItems: 'center' },
  avatar: { width: 100, height: 100, borderRadius: 50 },
  editBadge: { position: 'absolute', bottom: 0, right: 0, width: 28, height: 28, borderRadius: 14, backgroundColor: '#000', alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#fff' },
  userName: { fontSize: 20, fontWeight: '800' },
  userEmail: { fontSize: 14, opacity: 0.6 },
  tabBar: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#eee', marginBottom: 20 },
  tab: { flex: 1, alignItems: 'center', paddingVertical: 15, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  activeTab: { borderBottomColor: '#000' },
  tabText: { fontSize: 12, fontWeight: '600', opacity: 0.6 },
  activeTabText: { opacity: 1, color: '#000' },
  section: { paddingHorizontal: 20 },
  sectionTitle: { fontSize: 14, fontWeight: '800', opacity: 0.5, textTransform: 'uppercase', marginBottom: 12 },
  card: { padding: 16, marginBottom: 16 },
  inputGroup: { marginBottom: 16 },
  label: { fontSize: 12, fontWeight: '700', marginBottom: 6, opacity: 0.6 },
  input: { borderWidth: 1, borderColor: '#ddd', borderRadius: 10, padding: 12, fontSize: 15, color: '#000' },
  disabledInput: { backgroundColor: '#f9f9f9', borderColor: '#eee', color: '#666' },
  editBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 20, borderWidth: 1, borderColor: '#ddd' },
  configCard: { padding: 16, gap: 16 },
  configRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  configTitle: { fontSize: 16, fontWeight: '700' },
  configDesc: { fontSize: 12, opacity: 0.6 },
  configDivider: { height: 1, backgroundColor: '#eee', marginVertical: 4 },
  radioGroup: { flexDirection: 'row', gap: 6 },
  radio: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 8, borderWidth: 1, borderColor: '#eee' },
  logoutBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 40, padding: 16 },
  logoutText: { color: '#EF4444', fontWeight: '700', fontSize: 16 },
});